name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install

    - name: Check code style
      run: composer check-cs
    
    - name: Run unit tests
      run: vendor/bin/phpunit
