name: build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Installing PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        ini-values: memory_limit=-1

    - name: "Install composer dependencies"
      uses: "ramsey/composer-install@v2"

    - name: "Run test suite"
      run: "composer tests"
